Show number of images submitted in current session
ThundeRatz/labelling-web-app pull request #9
Opened 2017-03-06 20:15 UTC by erickotsuka

Achei que seria interessante mostrar esse número. Dá para mudar o estilo se acharem melhor. Talvez alguma melhoria para "lembrar" quantos cones a pessoa havia clicado na sessão anterior e continuar incrementando, sem precisar de um banco de dados, como gerar um link único para cada pessoa.
É possível também criar um banco de dados para fazer um sistema de ranking.

2017-03-06 21:40 UTC, tiagoshibata requested changes
Boa ideia, bem mais fácil que passar pro servidor e salvar no DB. Se quisermos dá pra adicionar mais features no futuro.

2017-03-06 21:40 UTC, tiagoshibata commented on labelling_web_app/templates/label.html
> +      document.getElementById("number_of_submits").innerHTML = "Number of images submitted in this session: " + submits;
Não dá pra atualizar só o número?

2017-03-07 20:23 UTC, erickotsuka commented on labelling_web_app/templates/label.html
> +      document.getElementById("number_of_submits").innerHTML = "Number of images submitted in this session: " + submits;
Pronto.

2017-03-07 21:30 UTC, tiagoshibata approved these changes
👍 Valeu, pode dar merge quando quiser.

2017-03-08 05:00 UTC, tiagoshibata reviewed
Algo a mais: Eu nomearia `number_of_submits` como `submission_count`, mas por se não tiver mais nada a mudar pode deixar assim.

2017-03-08 05:00 UTC, tiagoshibata commented on labelling_web_app/templates/label.html
> +      <button id="submit-button" type="button" style="position:absolute;left:50%;">Submit</button>
Era necessário atribuir o callback por código?

2017-03-08 05:09 UTC, erickotsuka commented on labelling_web_app/templates/label.html
> +      <button id="submit-button" type="button" style="position:absolute;left:50%;">Submit</button>
Não sei se era necessário, mas fiz isso para chamar a função initializeSubmits() antes. Fiquei em dúvida mesmo em que fazer.

2017-03-08 05:12 UTC, tiagoshibata commented on labelling_web_app/templates/label.html
> +      <button id="submit-button" type="button" style="position:absolute;left:50%;">Submit</button>
Mas `initiateSubmits()` ainda está sendo chamada depois, não?

2017-03-08 05:25 UTC, erickotsuka commented on labelling_web_app/templates/label.html
> +      <button id="submit-button" type="button" style="position:absolute;left:50%;">Submit</button>
Mudei e testei aqui e continua funcionando. Acho que não era necessário mesmo.

2017-03-08 05:29 UTC, tiagoshibata approved these changes

2017-03-08 05:29 UTC, merged